# Generated by Django 3.1.1 on 2020-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postm',
            name='man_of_the_match',
            field=models.TextField(default=0, max_length=200),
        ),
    ]
