# Generated by Django 3.1.1 on 2020-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_postm_man_of_the_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postm',
            name='man_of_the_match',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
