# Generated by Django 3.1.1 on 2020-10-08 07:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0004_auto_20201008_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostM',
            new_name='MatchReport',
        ),
    ]
