# Generated by Django 3.1.1 on 2020-10-08 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0005_auto_20201008_0737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchReport',
            new_name='Post',
        ),
    ]
