# Generated by Django 3.1.1 on 2020-10-10 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0006_auto_20201008_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Match',
        ),
    ]
