# Generated by Django 3.1.1 on 2020-10-10 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0007_auto_20201010_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='Post',
        ),
    ]
