# Generated by Django 3.1.1 on 2020-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20201010_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
