# Generated by Django 3.1.1 on 2020-11-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20201121_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
