# Generated by Django 3.1.1 on 2020-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20201130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
