# Generated by Django 3.1.1 on 2020-10-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='surname',
            field=models.CharField(default='', max_length=80),
        ),
    ]
