# Generated by Django 3.1.1 on 2020-10-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='surname',
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
