# Generated by Django 3.1.1 on 2020-10-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201004_0744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
